approvedGitRepositories:
  - "**"

defaultSemverRangePrefix: ""

enableImmutableInstalls: true

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 2880

npmScopes:
  navikt:
    npmAlwaysAuth: true
    npmAuthToken: "${NODE_AUTH_TOKEN:-}"
    npmRegistryServer: "https://npm.pkg.github.com"
