apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: soknad-alerts
  labels:
    team: aap
    app: soknad
  namespace: aap
spec:
  receivers:
    slack:
      channel: '#aap-github'
  alerts:
    - alert: soknad-app-nede
      expr: kube_deployment_status_replicas_unavailable{deployment="soknad",job="kubernetes-service-endpoints"} > 0
      for: 5m
      description: "soknad har utilgjengelige podder i aap"
      action: "kubectl describe pod -l app=soknad -n aap` for events og `kubectl get pods -l app=soknad -n aap` for å se feilende podder"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: soknad-kontinuerlig-restart
      expr: sum(increase(kube_pod_container_status_restarts_total{container=~"soknad"}[5m])) by (container) > 2
      for: 2m
      description: "soknad har restartet flere ganger de siste 5 minuttene!"
      action: "Se `kubectl describe pod soknad` for events, og `kubectl logs soknad` for logger"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: soknai-mangler-metrikker
      expr: absent(up{app=~"soknad",job="kubernetes-pods"})
      for: 2m
      description: "soknad rapporterer ingen metrikker i aap"
      action: "Sjekk om soknad i aap er oppe"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: høy feilrate i logger
      expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="soknad",log_level=~"Error"}[10m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="soknad"}[10m]))) > 15
      for: 5m
      action: "<https://logs.adeo.no/goto/1d394a6a4c647c93c51eda75e60999ed|Check logs>"
