apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "aap-soknad"
  namespace: "aap"
  labels:
    "team": "aap"
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - "https://aap-soknad.ekstern.dev.nav.no/"
  liveness:
    path: "/aap/soknad/api/internal/isAlive"
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/aap/soknad/api/internal/isReady"
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
  accessPolicy:
    outbound:
      external:
        - host: "dekoratoren.ekstern.dev.nav.no"