apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "250M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
  name: "soknad"
  namespace: "aap"
  labels:
    "team": "aap"
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: "/aap/soknad/api/internal/isAlive"
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/aap/soknad/api/internal/isReady"
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 4
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 512Mi
  prometheus:
    enabled: true
    path: /aap/soknad/api/internal/prometheus/
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: elastic
        - id: loki
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
      level: Level4
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  env:
  {{#each env}}
    - name: {{this.name }}
      value: {{this.value}}
  {{/each}}
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: innsending
        - application: oppslag
        - application: nav-dekoratoren
          namespace: personbruker
      external:
        {{#each externals as |host|}}
        - host: {{host}}
        {{/each}}
