apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "aap-soknad"
  namespace: "aap"
  labels:
    "team": "aap"
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: "/aap/internal/isAlive"
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/aap/internal/isready"
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
  prometheus:
    enabled: true
    path: "/metrics"
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}