ingresses:
- "https://aap-soknad.nav.no"
env:
- name: DECORATOR_URL
  value: "https://dekoratoren.nav.no"
- name: DECORATOR_ENV
  value: "prod"
- name: LOGINSERVICE_URL
  value: "https://loginservice.nav.no/login"
- name: APP_URL
  value: "https://aap-soknad.nav.no"
- name: SOKNAD_API_URL
  value: "https://aap-soknad-api.intern.nav.no"
- name: SOKNAD_API_AUDIENCE
  value: "prod-gcp:aap:aap-soknad-api"
externals:
  - "dekoratoren.dev.no"
