ingresses:
- "https://www.nav.no/aap/soknad"
env:
- name: DECORATOR_URL
  value: "https://dekoratoren.nav.no"
- name: DECORATOR_ENV
  value: "prod"
- name: APP_URL
  value: "https://aap-soknad.nav.no"
- name: SOKNAD_API_URL
  value: "http://soknad-api"
- name: SOKNAD_API_AUDIENCE
  value: "prod-gcp:aap:soknad-api"
- name: RUNTIME_ENVIRONMENT
  value: "prod"
- name: DECORATOR_ENV
  value: "prod"
- name:  SOKNAD_API_URL
  value: "http://soknad-api"
- name:  SOKNAD_API_AUDIENCE
  value: "prod-gcp:aap:soknad-api"
- name:  ENABLE_SENTRY
  value: "enabled"
externals:
  - "www.nav.no"
