name: "Historisk snapshot av mocket søknad"
on:
  workflow_dispatch:
#  push:
#    branches:
#      - "labs-historisk-**"
env:
  IMAGE_BASE: europe-north1-docker.pkg.dev/${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}/aap/${{ github.event.repository.name }}-historisk-${{ github.ref_name }}
jobs:
  buildMock:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.image.outputs.image }}
    env:
      NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      SKIP_YARN_COREPACK_CHECK: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com
          cache: yarn
      - name: Enable Corepack
        run: corepack enable
      - uses: gacts/github-slug@v1
        id: slug
        with:
          to-slug: aap-soknad-${{ github.ref_name }}
      - name: install dependencies Yarn
        run: yarn install --immutable
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Copy env-file # TODO: Se om vi kan finne en bedre løsning her på sikt
        run: cp .nais/dev-mock.env .env.local
      - name: run build
        run: yarn run build
      - uses: nais/docker-build-push@v0
        with:
          team: aap
          image_suffix: ${{ steps.slug.outputs.slug }}
          tag: ${{ github.sha }}
  "deployAppToLabsHistorisk":
    name: "Deploy branch to dev"
    needs: buildMock
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: gacts/github-slug@v1
        id: slug
        with:
          to-slug: aap-soknad-${{ github.ref_name }}
      - uses: nais/login@v0
        id: login
        with:
          team: aap
      - uses: nais/deploy/actions/deploy@v2
        env:
          PRINT_PAYLOAD: true
          CLUSTER: dev-gcp
          RESOURCE: .nais/historisk-dev-mock.yaml
          VAR: image=${{ steps.login.outputs.registry }}/${{ github.event.repository.name }}${{ steps.slug.outputs.slug }}:${{ github.sha }},ingress=https://${{ steps.slug.outputs.slug }}.ekstern.dev.nav.no,appname=${{ steps.slug.outputs.slug }},replicas=1,branchState=alive
