name: "Labs:  delete historisk snapshot"
on: delete
env:
  "IMAGE": "ghcr.io/${{ github.repository }}-labs-historisk:${{ github.sha }}"
  "APP_NAME": "aap-soknad-${{ github.event.ref }}"
jobs:
  deploy-branch-to-labs-gcp:
    if: startsWith(github.event.ref, 'labs-historisk')
    name: Delete branch labs-gcp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scale down dev-gcp-mock-historisk
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: ".nais/historisk-dev-mock.yaml"
          VAR: image=${{ env.IMAGE }},appname=${{env.APP_NAME}},ingress=https://${{env.APP_NAME}}.ekstern.dev.nav.no,replicas=0,branchState=deleted
