name: Update dependabot config

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 3'

jobs:
  checkForConfigUpdate:
    uses: navikt/aap-workflows/.github/workflows/dependabot-frontend-next-config-updater.yml@main
    permissions:
      contents: write
      id-token: write
      packages: write
      pull-requests: write
